name: Security Scan Example

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    uses: ./.github/workflows/security.yml
    with:
      # Show the actual keys/secrets found by TruffleHog
      show_keys: true
      # Enable webhook notifications for security alerts
      notify_webhook: true
    secrets:
      webhook_url: ${{ secrets.SECURITY_WEBHOOK_URL }}
# Example with different configurations:
#
# jobs:
#   security-scan:
#     uses: ./.github/workflows/security.yml
#     with:
#       # Hide the actual keys/secrets (default behavior)
#       show_keys: false
#       # Disable webhook notifications
#       notify_webhook: false
#     secrets:
#       webhook_url: ${{ secrets.SECURITY_WEBHOOK_URL }}
#
# Available inputs:
# - show_keys: boolean (default: false)
#   - true: Display the actual keys/secrets found by TruffleHog
#   - false: Hide the actual keys/secrets (recommended for security)
#
# - notify_webhook: boolean (default: true)
#   - true: Send webhook notifications for security alerts
#   - false: Skip webhook notifications (useful for testing or when webhook is not needed)
#
# Required secrets:
# - webhook_url: The webhook URL where security alerts will be sent
